language: node_js
node_js:
- '0.10'
branches:
  only:
  - 5.0-wip
before_script:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git config --global user.email "mark@zurb.com"
- git config --global user.name "mhayes"
script:
- npm install grunt
- npm install grunt-cli
- grunt compile
after_script:
- git clone https://mhayes:${GH_TOKEN}@github.com/zurb/bower-foundation.git
- cp -r dist/assets/* bower-foundation-css/
- cd bower-foundation-css
- git remote rm origin
- git remote add origin https://mhayes:${GH_TOKEN}@github.com/zurb/bower-foundation-css.git
- git add .
- git commit -m "Foundation build to bower-foundation-css"
- git push -fq origin master
- echo -e "Done with magic\n"
env:
  global:
    secure: USNBfNsfQFF6UgNzXRXA+8mWc66WvOUXjIH5PRjbBRUfUFZkt0a74P7uW/IMJZ0XlQwbWCphzv6Rh1qfI5bbmh6nwlJtBgP6KCc/GrPyN61YrudmPZfiNrHFkylhELz82CE6oWZjZGRwlCsLa3IADo27azmQx7kJhko5t3war5A=
